name: Build
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_sdk_job:
    name: Build SDK
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clj/esp8266-gcc:latest
    steps:
      - name: Get release date
        id: get_release_date
        run: |
          release_date=$(echo ${{ github.ref_name }} | cut -d- -f2)
          echo "::set-output name=release_date::$release_date"
        if: startsWith(github.ref_name, 'release-')
      - name: Checkout nim-esp8266-sdk
        uses: actions/checkout@v2
      - name: Checkout c2nim-esp8266
        uses: actions/checkout@v2
        with:
          repository: clj/c2nim-esp8266
          path: 'c2nim-esp8266'
          submodules: true
      - run: nim --version
      - run: nimble bootstrap -y
        working-directory: c2nim-esp8266
      - run: nimble build -y
        working-directory: c2nim-esp8266
      - run: make C2NIM=c2nim-esp8266/c2nim_esp8266
      - run: make C2NIM=c2nim-esp8266/c2nim_esp8266 dist RELEASE_TAG=${{ steps.get_release_date.outputs.release_date }}
        if: ${{ startsWith(github.ref_name, 'release-') }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref_name, 'release-')
        with:
          body_path: ${{ github.workspace }}/release-notes/${{ steps.get_release_date.outputs.release_date }}.md
          files:
            dist/nim_esp8266_nonos_sdk-*
          fail_on_unmatched_files: true
  build_docker_image_job:
    name: Build Container
    needs: build_sdk_job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref_name, 'release-')
    steps:
      - name: Get release date
        id: get_release_date
        run: |
          release_date=$(echo ${{ github.ref_name }} | cut -d- -f2)
          echo "::set-output name=release_date::$release_date"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish esp8266-nim-sdk Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker"
          target: esp8266-nim-sdk
          tags: ghcr.io/clj/esp8266-nim-sdk:latest
          push: true
          build-args: |
            NIM_ESP_SDK_VERSION=${{ steps.get_release_date.outputs.release_date }}